# Generated by Django 3.2 on 2022-05-22 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('connection_reason', models.CharField(choices=[('a Divorce', 'Divorce'), ('anxiety', 'Anxiety'), ('their physical wellbeing', 'Physical Wellbeing'), ('their sexuality', 'Sexuality'), ('their finances', 'Finance'), ('their marriage', 'Marriage'), ('grief', 'Grief'), ('their religion', 'Religion'), ('depression', 'Depression'), ('their mental health', 'Mental Health'), ('loss', 'Loss'), ('their relationships', 'Relationship'), ('their gender identity', 'Gender Identity'), ('loneliness', 'Loneliness'), ('their health', 'Health'), ('their belief', 'Belief'), ('worries about death', 'Death'), ('their weight', 'Weight')], max_length=30)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('response_decision', models.CharField(blank=True, choices=[('accept', 'Yes'), ('deny', 'No')], max_length=30, null=True)),
                ('relation', models.CharField(choices=[('family', 'Family'), ('work collegues', 'Work Collegues'), ('close friends', 'Close Friends'), ('friends', 'Friends')], max_length=30)),
                ('custom_response_text', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('sender_username', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
