# Generated by Django 3.2 on 2022-05-21 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('connection_reason', models.CharField(choices=[('lonliness', 'Lonliness'), ('depression', 'Depression')], max_length=30)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('response_decision', models.CharField(blank=True, choices=[('deny', 'No'), ('accept', 'Yes')], max_length=30, null=True)),
                ('custom_response_text', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
