# Generated by Django 3.2 on 2022-05-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('work collegues', 'Work Collegues'), ('close friends', 'Close Friends')], default='friends', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_reason',
            field=models.CharField(choices=[('loneliness', 'Loneliness'), ('depression', 'Depression')], max_length=30),
        ),
    ]
