# Generated by Django 3.2 on 2022-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_reason',
            field=models.CharField(choices=[('their finances', 'Finance'), ('worries about death', 'Death'), ('their religion', 'Religion'), ('their mental health', 'Mental Health'), ('their marriage', 'Marriage'), ('depression', 'Depression'), ('their weight', 'Weight'), ('grief', 'Grief'), ('their health', 'Health'), ('anxiety', 'Anxiety'), ('loss', 'Loss'), ('their belief', 'Belief'), ('their gender identity', 'Gender Identity'), ('their relationships', 'Relationship'), ('their physical wellbeing', 'Physical Wellbeing'), ('loneliness', 'Loneliness'), ('their sexuality', 'Sexuality'), ('a Divorce', 'Divorce')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('work collegues', 'Work Collegues'), ('family', 'Family'), ('close friends', 'Close Friends'), ('friends', 'Friends')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='response_decision',
            field=models.CharField(blank=True, choices=[('deny', 'No'), ('accept', 'Yes')], max_length=30, null=True),
        ),
    ]
