# Generated by Django 3.2 on 2022-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0002_auto_20220522_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_reason',
            field=models.CharField(choices=[('their relationships', 'Relationship'), ('their health', 'Health'), ('their gender identity', 'Gender Identity'), ('loneliness', 'Loneliness'), ('their marriage', 'Marriage'), ('their religion', 'Religion'), ('grief', 'Grief'), ('depression', 'Depression'), ('a Divorce', 'Divorce'), ('their mental health', 'Mental Health'), ('worries about death', 'Death'), ('anxiety', 'Anxiety'), ('their finances', 'Finance'), ('their sexuality', 'Sexuality'), ('their weight', 'Weight'), ('their belief', 'Belief'), ('their physical wellbeing', 'Physical Wellbeing'), ('loss', 'Loss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('close friends', 'Close Friends'), ('friends', 'Friends'), ('work collegues', 'Work Collegues'), ('family', 'Family')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='response_decision',
            field=models.CharField(blank=True, choices=[('accept', 'Yes'), ('deny', 'No')], max_length=30, null=True),
        ),
    ]
