# Generated by Django 3.2 on 2022-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0002_auto_20220521_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('family', 'Family'), ('work collegues', 'Work Collegues'), ('friends', 'Friends'), ('close friends', 'Close Friends')], max_length=30),
        ),
    ]
