# Generated by Django 3.2 on 2022-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0002_auto_20220521_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='sender_username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('family', 'Family'), ('close friends', 'Close Friends'), ('friends', 'Friends'), ('work collegues', 'Work Collegues')], max_length=30),
        ),
    ]
