# Generated by Django 3.2 on 2022-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionrequest', '0003_auto_20220522_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='connection_reason',
            field=models.CharField(choices=[('their mental health', 'Mental Health'), ('depression', 'Depression'), ('their gender identity', 'Gender Identity'), ('their marriage', 'Marriage'), ('their religion', 'Religion'), ('loss', 'Loss'), ('their finances', 'Finance'), ('anxiety', 'Anxiety'), ('loneliness', 'Loneliness'), ('their weight', 'Weight'), ('their health', 'Health'), ('their physical wellbeing', 'Physical Wellbeing'), ('worries about death', 'Death'), ('their sexuality', 'Sexuality'), ('grief', 'Grief'), ('their relationships', 'Relationship'), ('their belief', 'Belief'), ('a Divorce', 'Divorce')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='relation',
            field=models.CharField(choices=[('family', 'Family'), ('close friends', 'Close Friends'), ('work collegues', 'Work Collegues'), ('friends', 'Friends')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='response_decision',
            field=models.CharField(blank=True, choices=[('deny', 'No'), ('accept', 'Yes')], max_length=30, null=True),
        ),
    ]
